name: pl_api_helper
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  connectivity_plus: ^6.1.5
  dio: ^5.9.0
  flutter:
    sdk: flutter
  http: ^1.5.0
  mockito: ^5.4.6
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
  
      some_platform:
        pluginClass: somePluginClass
